"""
Type stubs for _hsv Cython module.
"""

from typing import Tuple

def hsv_to_rgb(h: float, s: float, v: float) -> Tuple[int, int, int]: ...
def rgb_to_hsv(r: int, g: int, b: int) -> Tuple[float, float, float]: ...
def generate_sv_gradient_rgba(hue: float, width: int, height: int) -> bytes: ...
def generate_hue_gradient_rgba(width: int, height: int, vertical: bool = ...) -> bytes: ...